### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'withdrawal'

### ISSUE THREAD

**Issue by isujosh** [Flo-Schilli/homeassistant-grohe_sense#37]
My integration has started to error in HA. Details below:

Source: custom_components/grohe_sense/entities/grohe_sense_guard.py:45
integration: Grohe Sense ([documentation](https://github.com/Flo-Schilli/homeassistant-grohe_sense), [issues](https://github.com/Flo-Schilli/homeassistant-grohe_sense/issues))
First occurred: 16:11:00 (1 occurrences)
Last logged: 16:11:00

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/grohe_sense/entities/grohe_sense_guard.py", line 45, in _handle_coordinator_update
    self._value = self._coordinator.data.withdrawal
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'withdrawal'

and also:

Logger: custom_components.grohe_sense.entities.grohe_sense_update_coordinator
Source: custom_components/grohe_sense/entities/grohe_sense_update_coordinator.py:143
integration: Grohe Sense ([documentation](https://github.com/Flo-Schilli/homeassistant-grohe_sense), [issues](https://github.com/Flo-Schilli/homeassistant-grohe_sense/issues))
First occurred: 16:11:00 (1 occurrences)
Last logged: 16:11:00

Error updating Grohe Sense data: 'NoneType' object has no attribute 'items'

Environment details:

Core: 2024.12.0
Supervisor: 2024.11.4
Operating System: 14.0
Frontend: 20241127.4

**Comment by Flo-Schilli** [comment]
Hi,

thanks for opening this issue. I'll have a look into it. Can you please tell me which version of the integration you're using. I guess - just from that error - you're having a Sense Guard, right?

**Comment by isujosh** [comment]
I'm using version v0.9.12

**Comment by Flo-Schilli** [comment]
Thanks for the info. 
Can you please check with the version 0.10.1, so with the latest version.

The Sense guard version in general should be fine 😊

**Comment by Flo-Schilli** [comment]
So it should be solved with the latest version on main. Would be great if you could verify that.

**Comment by isujosh** [comment]
Seems to be - haven't seen the error since the update to 0.10.1. Happy to close the issue.
